from typing import Any, Literal, TypedDict

from app.schemas.pedagogical_move import PedagogicalMove


RouterRoute = Literal[
    "direct_tutor",
    "planned_tutor",
]

TeachingPhase = Literal[
    "initial",
    "reteaching",
]

TeachingProgressStatus = Literal[
    "continue_teaching",
    "ready_for_assessment",
]

AdaptiveLifecycleStatus = Literal[
    "not_started",
    "active",
    "completed",
    "aborted",
]


class TutorState(TypedDict, total=False):
    """Shared state for the multi-turn AdaptMath tutoring workflow."""

    # External profile data owned by Malindu.
    student_id: str
    age: int

    # One LangGraph thread spans a complete problem/session. Each assessment
    # cycle is a separate adaptive attempt with an explicit canonical BKT skill.
    thread_id: str
    attempt_id: str | None
    adaptive_attempt_index: int
    target_skill: str
    adaptive_lifecycle_status: AdaptiveLifecycleStatus
    mastery_before: float
    attempt_started_at: str

    # Current mathematics problem.
    question: str

    # External learner/topic context owned by Hamooth.
    topic: str
    subtopic: str | None
    relevant_history: list[dict[str, Any]]
    previous_errors: list[str]
    previous_strategies: list[str]

    # Current MathDial pedagogical move selected by Omash.
    # It is consumed for one teacher turn and never selected by this component.
    pedagogical_move: PedagogicalMove | None
    adaptive_turn_diagnostics: dict[str, Any]
    # Identity of the Tutor action awaiting its next learner observation.
    # These are attempt-local and never derived from thread-global turn_count.
    action_event_id: str
    action_turn_index: int
    adaptive_completion_result: dict[str, Any]
    completed_attempt_id: str

    # Problem-level ML evidence and Router result.
    complexity_score: float
    route: RouterRoute
    route_reason: str

    # Optional overall plan when Router selects planned_tutor.
    planner_output: dict[str, Any]

    # Verified math is prepared once and reused across teacher turns.
    verified_math_evidence: list[dict[str, str]]

    # Active teacher-student tutoring dialogue.
    conversation_history: list[dict[str, Any]]
    tutor_response: str
    latest_student_response: str
    turn_count: int
    teaching_phase: TeachingPhase
    teaching_status: TeachingProgressStatus
    teaching_progress_reason: str

    # Formal post-teaching assessment generated by Evaluator.
    assessment_questions: list[dict[str, Any]]
    student_answers: list[dict[str, Any]]
    evaluation_result: dict[str, Any]
    correct_answers: list[dict[str, Any]]
    wrong_answers: list[dict[str, Any]]
    needs_reteaching: bool

    # Optional cross-session Memory acknowledgement and checkpointed retry
    # queue. These fields never feed BKT, C3, MD6, MRB1, LinTS, or reward.
    memory_update_result: dict[str, Any] | None
    memory_write_pending: bool
    memory_pending_write: dict[str, Any] | None
    memory_pending_writes: list[dict[str, Any]]

    # Number of completed assessment failures that triggered a new reteaching
    # cycle. It is tracking evidence only, not a pedagogical threshold.
    reteach_round: int
